### ISSUE TITLE
Use yaml lists instead of additional priority attribute

### ISSUE THREAD

**Issue by saily** [dalwar23/labelx#14]
## Feature request

Let's switch to yaml internal sorting with lists! Furthermore I would like to see all labels in `labels:` attribute and badges in `badges:` attribute. This would also allow to combine all configuration in one single `config.yaml` file if we want, but still can keep the separated files if preferred.

### primary goal:
- get rid of additional priority attribute by just using the list order for sorting

### secondary goal:
- make it more scalable for future extensions by not putting each config into a different file.

Today: 

```yaml
---
Bug:
  color: "#FF0000"
  description:
  description_html: ''
  text_color: "#FFFFFF"
  subscribed: false
  priority: 0
  is_project_label: true
Done:
  color: "#0033CC"
  description:
  description_html: ''
  text_color: "#FFFFFF"
  subscribed: false
  priority:
  is_project_label: true
```

Future:
```yaml
---
login:
  host: $CI_SERVER_URL
  protocol: <https>/<http>
  token: $CI_JOB_TOKEN
labels:
  - Bug:  # this would be highest prio
    color: "#FF0000"
    description:
    description_html: ""
    text_color: "#FFFFFF"
    subscribed: false
    is_project_label: true
  - Done:  # this would be 2nd highest prio
    color: "#0033CC"
    text_color: "#FFFFFF"
badges:
  - license:
    link_url: "%{project_path}/LICENSE"
    image_url: "https://img.shields.io/badge/License-MIT-blue.svg?style=flat-square"

```
